<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Modulos\Equipamentos\Apresentacao\Views\" />
    <Folder Include="Modulos\Equipamentos\Dominio\" />
    <Folder Include="Modulos\Equipamentos\Infraestrutura\" />
  </ItemGroup>

</Project>
